# Generated by Django 5.1.4 on 2026-05-13 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name_uz', models.CharField(max_length=40, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=40, verbose_name='Nomi (RU)')),
                ('lat_min', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lat_max', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon_min', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon_max', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_last_frost_doy', models.IntegerField(default=80, verbose_name='Bahorgi oxirgi sovuq (yil kuni)')),
                ('avg_first_frost_doy', models.IntegerField(default=290, verbose_name='Kuzgi birinchi sovuq (yil kuni)')),
                ('annual_rainfall_mm', models.IntegerField(default=300, verbose_name="Yillik yog'ingarchilik (mm)")),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ('name_uz',),
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('name_uz', models.CharField(max_length=80, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=80, verbose_name='Nomi (RU)')),
                ('name_lat', models.CharField(blank=True, max_length=120, verbose_name='Lotincha nom')),
                ('category', models.CharField(default='sabzavot', help_text='sabzavot | meva | don | gul | dorivor', max_length=20, verbose_name='Kategoriya')),
                ('icon_name', models.CharField(default='leaf', help_text='Lucide icon kalit: leaf | carrot | apple | wheat | flower | sprout | tree-deciduous', max_length=40, verbose_name='Icon')),
                ('min_soil_temp_c', models.IntegerField(default=0, verbose_name='Min tuproq harorati °C')),
                ('optimal_soil_temp_c', models.IntegerField(default=0, verbose_name='Optimal tuproq harorati °C')),
                ('frost_sensitive', models.BooleanField(default=False, verbose_name='Sovuqdan zaif')),
                ('plant_window_start_month', models.IntegerField(default=3, verbose_name='Ekish davri boshi (oy)')),
                ('plant_window_end_month', models.IntegerField(default=5, verbose_name='Ekish davri oxiri')),
                ('days_to_harvest_min', models.IntegerField(default=80, verbose_name='Hosilgacha kun (min)')),
                ('days_to_harvest_max', models.IntegerField(default=120, verbose_name='Hosilgacha kun (max)')),
                ('water_freq_days', models.IntegerField(default=5, verbose_name="Sug'orish chastotasi (kun)")),
                ('drought_tolerant', models.BooleanField(default=False, verbose_name='Quruqlikka chidamli')),
                ('flood_tolerant', models.BooleanField(default=False, verbose_name='Suvga chidamli')),
                ('soil_type', models.CharField(default='qum-tuproq', max_length=80, verbose_name='Tuproq turi')),
                ('ph_min', models.DecimalField(decimal_places=1, default=6.0, max_digits=3, verbose_name='pH min')),
                ('ph_max', models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='pH max')),
                ('sun_hours_min', models.IntegerField(default=6, verbose_name='Quyosh soatlari (min)')),
                ('soil_prep_uz', models.TextField(blank=True, verbose_name='Tuproqni tayyorlash')),
                ('planting_method_uz', models.TextField(blank=True, verbose_name='Ekish usuli')),
                ('care_tips_uz', models.TextField(blank=True, verbose_name='Parvarish maslahati')),
                ('common_pests', models.TextField(blank=True, verbose_name='Asosiy zararkunandalar')),
                ('common_varieties', models.JSONField(blank=True, default=list, verbose_name='Navlar')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='Rasm URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ekin',
                'verbose_name_plural': 'Ekinlar',
                'ordering': ('name_uz',),
                'indexes': [models.Index(fields=['category'], name='crops_crop_categor_7f15f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=8)),
                ('irrigation', models.CharField(choices=[('drip', 'Tomchi'), ('sprinkler', "Yomg'irlash"), ('manual', "Qo'l"), ('none', "Yo'q")], default='manual', max_length=20)),
                ('plot_size_m2', models.IntegerField(blank=True, null=True)),
                ('planned_plant_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('notify', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ekish rejasi',
                'verbose_name_plural': 'Ekish rejalari',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='crops_cropp_user_id_6eecf2_idx')],
            },
        ),
    ]
