# Generated by Django 5.1.4 on 2026-05-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_platform',
            field=models.CharField(blank=True, help_text='android | ios | web', max_length=20, verbose_name='Qurilma platformasi'),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, help_text='Firebase Cloud Messaging — push xabarlari uchun', max_length=255, verbose_name='FCM token'),
        ),
    ]
