# Generated by Django 5.1.4 on 2026-05-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_image_url_and_reseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_seller',
            field=models.CharField(blank=True, help_text='Sotuvchi nomi: Amazon, Aliexpress, Olcha, Uzum Market, va h.k.', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, help_text='Tashqi sotuv link (Amazon/Aliexpress/Olcha) — bossa shu yerga olib boradi', max_length=600),
        ),
    ]
