# Generated by Django 5.1.4 on 2026-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plant', 'Giyoh'), ('danger', 'Xavf'), ('camp', 'Dam olish'), ('water', 'Suv'), ('viewpoint', 'Manzara'), ('road', "Yo'l")], max_length=12)),
                ('label', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xarita markeri',
                'verbose_name_plural': 'Xarita markerlari',
                'ordering': ('type', 'label'),
            },
        ),
    ]
