# Generated by Django 5.1.4 on 2026-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('latin', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(choices=[('giyoh', 'Giyoh'), ('daraxt', 'Daraxt'), ('gul', 'Gul'), ('jonivor', 'Jonivor'), ('hasharot', 'Hasharot'), ('qush', 'Qush'), ('qoziqorin', 'Qoziqorin')], max_length=16)),
                ('icon_name', models.CharField(default='leaf', help_text='Frontend icon key: leaf, tree, flower, snake, paw, bird...', max_length=40)),
                ('color_class', models.CharField(default='bg-primary-100 text-primary-700', help_text='Tailwind class for tile background', max_length=80)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('habitat', models.TextField(blank=True)),
                ('uses', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('first_aid', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='species/')),
                ('image_url', models.URLField(blank=True, help_text='Optional external image (Unsplash, Wikipedia)')),
                ('red_book', models.BooleanField(default=False, help_text='Mahalliy Qizil kitobda')),
                ('iucn_status', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in Wild'), ('EX', 'Extinct'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], default='NE', max_length=4)),
                ('regions', models.CharField(blank=True, help_text="Mintaqa(lar), vergul bilan: 'Shahrisabz, G'arbiy Tyan-Shan'", max_length=240)),
                ('external_ref', models.URLField(blank=True, help_text='iNaturalist / GBIF / Wikipedia havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
                'ordering': ('name',),
            },
        ),
    ]
