# Generated by Django 5.1.4 on 2026-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='bloom_months',
            field=models.CharField(blank=True, help_text='Gulash oylari (vergul bilan): 4,5,6', max_length=50),
        ),
        migrations.AddField(
            model_name='species',
            name='fine_bhm_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='fine_bhm_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='halal_status',
            field=models.CharField(default='unknown', help_text='halal | makruh | haram | unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='species',
            name='harvest_months',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='species',
            name='is_edible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='is_honey_plant',
            field=models.BooleanField(default=False, help_text='Asalari uchun yaxshi?'),
        ),
        migrations.AddField(
            model_name='species',
            name='is_medicinal',
            field=models.BooleanField(default=False, help_text='Dorivor giyohmi?'),
        ),
        migrations.AddField(
            model_name='species',
            name='law_article',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='species',
            name='livestock_danger',
            field=models.CharField(default='safe', help_text='safe | toxic | deadly', max_length=10),
        ),
    ]
