# Generated by Django 5.1.4 on 2026-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_image_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('giyoh', 'Giyoh'), ('daraxt', 'Daraxt'), ('gul', 'Gul'), ('jonivor', 'Jonivor'), ('hasharot', 'Hasharot'), ('qush', 'Qush'), ('qoziqorin', 'Qoziqorin')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='species',
            name='halal_status',
            field=models.CharField(db_index=True, default='unknown', help_text='halal | makruh | haram | unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='species',
            name='is_edible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='is_honey_plant',
            field=models.BooleanField(db_index=True, default=False, help_text='Asalari uchun yaxshi?'),
        ),
        migrations.AlterField(
            model_name='species',
            name='is_medicinal',
            field=models.BooleanField(db_index=True, default=False, help_text='Dorivor giyohmi?'),
        ),
        migrations.AlterField(
            model_name='species',
            name='iucn_status',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in Wild'), ('EX', 'Extinct'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], db_index=True, default='NE', max_length=4),
        ),
        migrations.AlterField(
            model_name='species',
            name='livestock_danger',
            field=models.CharField(db_index=True, default='safe', help_text='safe | toxic | deadly', max_length=10),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(db_index=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='species',
            name='red_book',
            field=models.BooleanField(db_index=True, default=False, help_text='Mahalliy Qizil kitobda'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['category', 'red_book'], name='sp_cat_redbook_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['category', 'is_medicinal'], name='sp_cat_med_idx'),
        ),
    ]
