# Generated by Django 5.1.4 on 2026-04-14 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, unique=True)),
                ('category', models.CharField(choices=[('ilon', 'Ilon / chayon'), ('yirtqich', 'Yirtqich jonivor'), ('yiqilish', 'Qoyadan yiqilish'), ('yongin', "Yong'in"), ('zaharlanish', 'Zaharlanish'), ('boshqa', 'Boshqa')], max_length=20)),
                ('severity', models.CharField(choices=[('past', 'Past'), ('orta', "O'rta"), ('yuqori', 'Yuqori')], default='orta', max_length=8)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('korib_chiqilmoqda', "Ko'rib chiqilmoqda"), ('yechildi', 'Yechildi')], default='yangi', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hodisa',
                'verbose_name_plural': 'Hodisalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
